//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EP", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ep_lbl_Add {
            get {
                return ResourceManager.GetString("ep_lbl_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_AddNewGroup {
            get {
                return ResourceManager.GetString("ep_lbl_AddNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_AddNewJob {
            get {
                return ResourceManager.GetString("ep_lbl_AddNewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_AddSpeciality {
            get {
                return ResourceManager.GetString("ep_lbl_AddSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Answer 1.
        /// </summary>
        internal static string ep_lbl_AnswerAr1 {
            get {
                return ResourceManager.GetString("ep_lbl_AnswerAr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Answer 2.
        /// </summary>
        internal static string ep_lbl_AnswerAr2 {
            get {
                return ResourceManager.GetString("ep_lbl_AnswerAr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Answer 1.
        /// </summary>
        internal static string ep_lbl_AnswerEn1 {
            get {
                return ResourceManager.GetString("ep_lbl_AnswerEn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Answer 2.
        /// </summary>
        internal static string ep_lbl_AnswerEn2 {
            get {
                return ResourceManager.GetString("ep_lbl_AnswerEn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Back {
            get {
                return ResourceManager.GetString("ep_lbl_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Day.
        /// </summary>
        internal static string ep_lbl_BirthDay {
            get {
                return ResourceManager.GetString("ep_lbl_BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ep_lbl_btnCancel {
            get {
                return ResourceManager.GetString("ep_lbl_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ep_lbl_btnOK {
            get {
                return ResourceManager.GetString("ep_lbl_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_CanAcceptedConf {
            get {
                return ResourceManager.GetString("ep_lbl_CanAcceptedConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_CandDate {
            get {
                return ResourceManager.GetString("ep_lbl_CandDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_CandNotRegistred {
            get {
                return ResourceManager.GetString("ep_lbl_CandNotRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_CandStatus {
            get {
                return ResourceManager.GetString("ep_lbl_CandStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_CanRefuseReason {
            get {
                return ResourceManager.GetString("ep_lbl_CanRefuseReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha Error.
        /// </summary>
        internal static string ep_lbl_CaptchaError {
            get {
                return ResourceManager.GetString("ep_lbl_CaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Clear {
            get {
                return ResourceManager.GetString("ep_lbl_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Close {
            get {
                return ResourceManager.GetString("ep_lbl_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Confirmation {
            get {
                return ResourceManager.GetString("ep_lbl_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string ep_lbl_ContentAr {
            get {
                return ResourceManager.GetString("ep_lbl_ContentAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ep_lbl_ContentEn {
            get {
                return ResourceManager.GetString("ep_lbl_ContentEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copyright.
        /// </summary>
        internal static string ep_lbl_copyright {
            get {
                return ResourceManager.GetString("ep_lbl_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string ep_lbl_Count {
            get {
                return ResourceManager.GetString("ep_lbl_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string ep_lbl_CurrLang {
            get {
                return ResourceManager.GetString("ep_lbl_CurrLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /assets/css/SiteEn.css.
        /// </summary>
        internal static string ep_lbl_CurrLangCss {
            get {
                return ResourceManager.GetString("ep_lbl_CurrLangCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ep_lbl_Date {
            get {
                return ResourceManager.GetString("ep_lbl_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ep_lbl_Delete {
            get {
                return ResourceManager.GetString("ep_lbl_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ep_lbl_Edit {
            get {
                return ResourceManager.GetString("ep_lbl_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Education_Levels {
            get {
                return ResourceManager.GetString("ep_lbl_Education_Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_EducLevel {
            get {
                return ResourceManager.GetString("ep_lbl_EducLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_EducSpec {
            get {
                return ResourceManager.GetString("ep_lbl_EducSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ep_lbl_Email {
            get {
                return ResourceManager.GetString("ep_lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Email Format.
        /// </summary>
        internal static string ep_lbl_EmailValidator {
            get {
                return ResourceManager.GetString("ep_lbl_EmailValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        internal static string ep_lbl_EmptyMessasge {
            get {
                return ResourceManager.GetString("ep_lbl_EmptyMessasge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_ErrorPage {
            get {
                return ResourceManager.GetString("ep_lbl_ErrorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Exit {
            get {
                return ResourceManager.GetString("ep_lbl_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_FinancialClasse {
            get {
                return ResourceManager.GetString("ep_lbl_FinancialClasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_ForTheGroup {
            get {
                return ResourceManager.GetString("ep_lbl_ForTheGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Gender {
            get {
                return ResourceManager.GetString("ep_lbl_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_GenderAge {
            get {
                return ResourceManager.GetString("ep_lbl_GenderAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occured, Please contact technical support.
        /// </summary>
        internal static string ep_lbl_GenericError {
            get {
                return ResourceManager.GetString("ep_lbl_GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string ep_lbl_Group {
            get {
                return ResourceManager.GetString("ep_lbl_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_GroupCode {
            get {
                return ResourceManager.GetString("ep_lbl_GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_GroupDate {
            get {
                return ResourceManager.GetString("ep_lbl_GroupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Hide {
            get {
                return ResourceManager.GetString("ep_lbl_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePage.
        /// </summary>
        internal static string ep_lbl_HomePage {
            get {
                return ResourceManager.GetString("ep_lbl_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_InterviewResult {
            get {
                return ResourceManager.GetString("ep_lbl_InterviewResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_InterviewsResults {
            get {
                return ResourceManager.GetString("ep_lbl_InterviewsResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_JobCandCount {
            get {
                return ResourceManager.GetString("ep_lbl_JobCandCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_JobCandidats {
            get {
                return ResourceManager.GetString("ep_lbl_JobCandidats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_JobCandidature {
            get {
                return ResourceManager.GetString("ep_lbl_JobCandidature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_JobCode {
            get {
                return ResourceManager.GetString("ep_lbl_JobCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_JobConfSelection {
            get {
                return ResourceManager.GetString("ep_lbl_JobConfSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_JobCount {
            get {
                return ResourceManager.GetString("ep_lbl_JobCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_JobGroup {
            get {
                return ResourceManager.GetString("ep_lbl_JobGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_JobName {
            get {
                return ResourceManager.GetString("ep_lbl_JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Jobs {
            get {
                return ResourceManager.GetString("ep_lbl_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_JobSelection {
            get {
                return ResourceManager.GetString("ep_lbl_JobSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        internal static string ep_lbl_LangTextValue {
            get {
                return ResourceManager.GetString("ep_lbl_LangTextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar-QA.
        /// </summary>
        internal static string ep_lbl_LCulture {
            get {
                return ResourceManager.GetString("ep_lbl_LCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string ep_lbl_Login {
            get {
                return ResourceManager.GetString("ep_lbl_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        internal static string ep_lbl_LoginError {
            get {
                return ResourceManager.GetString("ep_lbl_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Logout {
            get {
                return ResourceManager.GetString("ep_lbl_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Mobile {
            get {
                return ResourceManager.GetString("ep_lbl_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ep_lbl_Name {
            get {
                return ResourceManager.GetString("ep_lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Nationaily {
            get {
                return ResourceManager.GetString("ep_lbl_Nationaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ep_lbl_Next {
            get {
                return ResourceManager.GetString("ep_lbl_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_NoAvalableCand {
            get {
                return ResourceManager.GetString("ep_lbl_NoAvalableCand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_NoAvalableJob {
            get {
                return ResourceManager.GetString("ep_lbl_NoAvalableJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Robot.
        /// </summary>
        internal static string ep_lbl_NotRobot {
            get {
                return ResourceManager.GetString("ep_lbl_NotRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string ep_lbl_Number {
            get {
                return ResourceManager.GetString("ep_lbl_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Error.
        /// </summary>
        internal static string ep_lbl_OTPError {
            get {
                return ResourceManager.GetString("ep_lbl_OTPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ep_lbl_Password {
            get {
                return ResourceManager.GetString("ep_lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_PrintCandMeeting {
            get {
                return ResourceManager.GetString("ep_lbl_PrintCandMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_PrintInterviewsLetters {
            get {
                return ResourceManager.GetString("ep_lbl_PrintInterviewsLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_QID {
            get {
                return ResourceManager.GetString("ep_lbl_QID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string ep_lbl_Required {
            get {
                return ResourceManager.GetString("ep_lbl_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string ep_lbl_Result {
            get {
                return ResourceManager.GetString("ep_lbl_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_ResultCanAccepted {
            get {
                return ResourceManager.GetString("ep_lbl_ResultCanAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_ResultCanRefuse {
            get {
                return ResourceManager.GetString("ep_lbl_ResultCanRefuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_ResultSponsRefuse {
            get {
                return ResourceManager.GetString("ep_lbl_ResultSponsRefuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Result.
        /// </summary>
        internal static string ep_lbl_ResultValidator {
            get {
                return ResourceManager.GetString("ep_lbl_ResultValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string ep_lbl_rtlltr {
            get {
                return ResourceManager.GetString("ep_lbl_rtlltr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ep_lbl_Search {
            get {
                return ResourceManager.GetString("ep_lbl_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string ep_lbl_SetPage {
            get {
                return ResourceManager.GetString("ep_lbl_SetPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string ep_lbl_SignInText {
            get {
                return ResourceManager.GetString("ep_lbl_SignInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignOut.
        /// </summary>
        internal static string ep_lbl_SignOutText {
            get {
                return ResourceManager.GetString("ep_lbl_SignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Specialities {
            get {
                return ResourceManager.GetString("ep_lbl_Specialities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_Speciality {
            get {
                return ResourceManager.GetString("ep_lbl_Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_SponJobsNeeded {
            get {
                return ResourceManager.GetString("ep_lbl_SponJobsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_SponJobsNeedGoup {
            get {
                return ResourceManager.GetString("ep_lbl_SponJobsNeedGoup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_SponJobsQuery {
            get {
                return ResourceManager.GetString("ep_lbl_SponJobsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_SponsorName {
            get {
                return ResourceManager.GetString("ep_lbl_SponsorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_SponsorType {
            get {
                return ResourceManager.GetString("ep_lbl_SponsorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ep_lbl_SponsRefuseReason {
            get {
                return ResourceManager.GetString("ep_lbl_SponsRefuseReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string ep_lbl_Submit {
            get {
                return ResourceManager.GetString("ep_lbl_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string ep_lbl_Title_Login {
            get {
                return ResourceManager.GetString("ep_lbl_Title_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string ep_lbl_Validate {
            get {
                return ResourceManager.GetString("ep_lbl_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ep_lbl_View {
            get {
                return ResourceManager.GetString("ep_lbl_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string ep_lbl_WelcomeMessage {
            get {
                return ResourceManager.GetString("ep_lbl_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        internal static string ep_lbl_Workspace {
            get {
                return ResourceManager.GetString("ep_lbl_Workspace", resourceCulture);
            }
        }
    }
}
